# default substitutions: https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
#
# https://github.com/GoogleCloudPlatform/cloud-build-samples
# https://github.com/GoogleCloudPlatform/cloud-builders-community
---

# IMAGE_NAME
# $COMMIT_SHA
steps:
- id: 'setup'
  name: 'docker.io/controlplane/cp-infra:latest'
  entrypoint: bash
  args:
    - -c
    - |
      set -Eeuxo pipefail

      make help

      cat <<EOF > /workspace/image_label.txt
      echo ${BRANCH_NAME} | sed 's,/,-,g' | awk '{print tolower($0)}')_${COMMIT_SHA}
      EOF

      cat <<EOF > /workspace/image_name.txt
      gcr.io/${PROJECT_ID}/${_PROJECT_NAME}:$(cat /workspace/image_label.txt)
      EOF

      printf "\n\nCONTAINER IMAGE:\t%s\n\n\n" "$(cat /workspace/image_name.txt)"

- id: 'container build'
  name: 'gcr.io/kaniko-project/executor:debug'
  entrypoint: sh
  args:
    - -c
    - |
      set -euxo pipefail

      /kaniko/executor --dockerfile=/workspace/Dockerfile \
        --context=/workspace \
        --context=dir://. \
        --destination="`cat /workspace/image_name.txt`" \
        --cache=true \
        --cache-ttl=99h \

substitutions:
  _PROJECT_NAME: gcloud-sdk

options:
  machineType: 'N1_HIGHCPU_32'
